### ISSUE TITLE
Duplicate entries when using `php:list`

### ISSUE THREAD

**Issue by jdecool** [Orbitale/Rymfony#13]
Hello,

I've tried `rymfony` with the latest Ubuntu release.

PHP binary seems to be duplicated in the list:

![image](https://user-images.githubusercontent.com/433926/89180717-9fbb1180-d592-11ea-8cc8-710749018d60.png)

Tested on Ubuntu 18.04

PHP binaries are installed through Brew for Linux.

**Comment by Pierstoval** [comment]
I'm currently working on a complete refactoring of how PHP is detected :) 

I intend to produce a result similar to Symfony's one, sorted by versions:

```
$ symfony local:php:list
┌─────────┬──────────────┬─────────┬─────────┬─────────────┬─────────┬─────────┐
│ Version │  Directory   │ PHP CLI │ PHP FPM │   PHP CGI   │ Server  │ System? │
├─────────┼──────────────┼─────────┼─────────┼─────────────┼─────────┼─────────┤
│ 7.4.2   │ E:\dev\php74 │ php.exe │         │ php-cgi.exe │ PHP CGI │ *       │
└─────────┴──────────────┴─────────┴─────────┴─────────────┴─────────┴─────────┘

The current PHP version is selected from default version in $PATH

To control the version used in a directory, create a .php-version file that contains the version number (e.g. 7.2 or 7.2.15).
```

**Comment by Pierstoval** [comment]
@jdecool I'm going to close this issue as it's supposed to be fixed on the latest builds, feel free to reopen if you still encounter this issue 👍

**Comment by jdecool** [comment]
I works great !

Thanks @Orbitaleio
