### ISSUE TITLE
[HTTP server] Add TLS support

### ISSUE THREAD

**Issue by Pierstoval** [Orbitale/Rymfony#32]
Should be possible to do this by using any popular package related to TLS with Hyper

**Comment by kevinpapst** [comment]
Yes please, for me this would be a critical feature that I am currently missing

**Comment by Pierstoval** [comment]
It seems that "Hyper with TLS" is a bit complex.

I decided to try to refactor the proxy server by using Warp. It uses Hyper internally, so maybe I can reuse the existing code.

I started the work on #37, let's see if it works 😉

**Comment by kevinpapst** [comment]
Cool, sent me a ping if you want me to test something.

**Comment by Pierstoval** [comment]
Very basic TLS support has been added, complementary to an entire refactor of the HTTP stack with Warp instead of Hyper 🥳

**Comment by kevinpapst** [comment]
Wow, awesome work! There is nothing new in the README, is it transparent usage like in:
- a certificate is generated automatically if not existing yet
- http and https are both answered
?

**Comment by Pierstoval** [comment]
For now, certificate is generated automatically and stored in `$HOME/.rymfony/`, and it doesn't answer HTTP-only, I've got more work to do on this, I just finished the first part but I don't have time to finish 😄 

It's in the pipeline though 😉 

I'd also like to add options to disable HTTPS if necessary, and add commands to create certificates for custom local domains other than 127.0.0.1 , but I have no idea on the ETA for all of this work 😉

**Comment by kevinpapst** [comment]
> it doesn't answer HTTP-only

Means: https only currently? Or do you mean both are always active right now? Sounds totally legit to me.

> add options to disable HTTPS if necessary

Do you have a use-case? Otherwise wait for a feature request 😁

> add commands to create certificates for custom local domains

Why not KISS and write sample docs for Linux how to generate and use the new certificate?

**Comment by Pierstoval** [comment]
> Means: https only currently? Or do you mean both are always active right now? Sounds totally legit to me.

For now, only HTTPS.
HTTP isn't taken in account.
I need to add another config option for this, but I guess it's going to be not extra complexity (like the [explanation here on SO](https://stackoverflow.com/questions/61423911/serve-on-multiple-portshttp-https-simultaneously-using-warp-framework-in-rust)).

> Do you have a use-case? Otherwise wait for a feature request 😁

Yep, mimic Symfony CLI as much as possible 😉 

> Why not KISS and write sample docs for Linux how to generate and use the new certificate?

Rymfony would still have to use them, and I guess that's what the `--p12` option is for in Symfony CLI, but I gotta check 😉
