### ISSUE TITLE
[PHP] Deserialize `php-versions.json` and reuse it at runtime

### ISSUE THREAD

**Issue by Pierstoval** [Orbitale/Rymfony#35]
For now, running `rymfony php:list` will save the resulting binaries paths into `php-versions.json`, using the great `serde` crate.

When running `rymfony serve`, the `crate::php::binaries::current()` function should deserialize this JSON file if it exists.

If it doesn't, it should run `crate::php::binaries::all()` to fetch them all, and print a _warning_ to tell the user to run the `rymfony php:list` command to improve performances.

The reason why I want this warning is to allow users to **never write anything on the disk**, in case they have a read-only filesystem.

This doesn't happen a lot, but a single call to `rymfony php:list` doesn't cost much, and can be automated if necessary.

**Comment by macintoshplus** [comment]
Released by #51. IMHO this issue can be closed.
