### ISSUE TITLE
[windows] how to provide directory to find PHP

### ISSUE THREAD

**Issue by macintoshplus** [Orbitale/Rymfony#55]
On Windows, I manage many PHP version with this arbo:

```
sites
    tools
        php72_nts
        php73_nts
        php74_nts
        php80_nts
        bin
            php72.bat
            php73.bat
            php74.bat
            php80.bat
```

The directory `d:\sites\tools\bin` is in `PATH` env variable.

![image](https://user-images.githubusercontent.com/814683/101835263-ce965500-3b3b-11eb-9610-3b8790a2318f.png)

How to allow Rymfony to found all php version?

**Comment by Pierstoval** [comment]
The PR you created for this is really interesting, and even though it works perfectly, I'd like to find a way to make sure users don't have to do anything for them to find their PHP binaries.

Isn't it possible to instead replace `\.exe$` with `\.(exe|bat|cmd)$` in the `binaries_from_dir()` function?

**Comment by Pierstoval** [comment]
Well, I did it in 9476bde27686d6a8929561aed65fd92458328cb2, so let's re-close this 👍
