### ISSUE TITLE
Add RYMFONY_PATH information on command php:list

### ISSUE THREAD

**Issue by macintoshplus** [Orbitale/Rymfony#58]
Add information about `RYMFONY_PATH` in the command help of `php:list`.

Add information about `RYMFONY_PATH` when no PHP version has be found.

@Pierstoval WDYT?

**Comment by Pierstoval** [comment]
What kind of information are you thinking about?

**Comment by macintoshplus** [comment]
On help:

`If you have PHP installed on custom folder, export the path into RYMFONY_PATH envonment variable before run "rymfony php:list --refresh" command `

On php:list run

`No PHP installation found. To provide your specific PHP installation path, export the path into RYMFONY_PATH envonment variable before run "rymfony php:list --refresh" command `

**Comment by Pierstoval** [comment]
Seems interesting, we might rework the wording but it's a good idea indeed :)

**Comment by macintoshplus** [comment]
@Pierstoval, you can suggest change on PR #59
