### ISSUE TITLE
Error on PNG assets access

### ISSUE THREAD

**Issue by jbcr** [Orbitale/Rymfony#64]
OS: Linux Ubuntu 20.04.1 LTS
PHP: 7.3.26 FPM
Rymfony: rymfony 0.1.0-ubuntu-829e2b47-nightly

Error when this image is requested:

```
 2021-01-14T07:46:56.687Z  INFO > GET /var/site/storage/images/_aliases/customer_logo_1/8/8/9/2/2988-3-fre-FR/customers%20logo.png
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: 
```

No error when I replace the space `%20` by an underscore.

**Comment by Pierstoval** [comment]
I've just pushed a fix to the latest build, can you redownload it when the Github Action finishes its job and tell me if the error is still there? 😉

**Comment by jbcr** [comment]
Work fine! Thanks for the quick fix.
