### ISSUE TITLE
Set-Cookie header lost in response

### ISSUE THREAD

**Issue by macintoshplus** [Orbitale/Rymfony#76]
If the serveur send multiple `Set-Cookie` response header, only one is received by the browser

![image](https://user-images.githubusercontent.com/814683/107827846-dcf52d00-6d87-11eb-9da6-0be1d74e12cd.png)

On left, Rymfony response, on right Symfony Cli response.

Rymfony and SymfonyCli serve the same project.

**Comment by Pierstoval** [comment]
Fixed by #77
